#samker_selfsignme:
#  #store certificates in dir
#  dir: "%env(SELFSIGNME_DIR)%"
#  #multiple template config for generating certificates
#  config:
#    #default config
#    default:
#      passphrase: false
#      days: "365"
#      algorythme:
#        digest_alg: "sha512"
#        x509_extensions: "v3_req"
#        private_key_bits: 2048
#        private_key_type: "!php/const:OPENSSL_KEYTYPE_RSA"
#      csr:
#        countryName: "%env(SELFSIGNME_CONFIG_DEFAULT_CSR_COUNTRYNAME)%"
#        stateOrProvinceName: "%env(SELFSIGNME_CONFIG_DEFAULT_CSR_STATE)%"
#        localityName: "%env(SELFSIGNME_CONFIG_DEFAULT_CSR_LOCALITY)%"
#        organizationName: "%env(SELFSIGNME_CONFIG_DEFAULT_CSR_ORGNAME)%"
#        organizationalUnitName: "%env(SELFSIGNME_CONFIG_DEFAULT_CSR_ORGUNIT)%"
#        commonName: null
#        emailAddress: "%env(SELFSIGNME_CONFIG_DEFAULT_CSR_EMAIL)%"
#
#  survey:
#      extensions: [ "pem", "key", "p12" ]
#      mailfrom: "%env(SELFSIGNME_SURVEY_MAILFROM)%"
#      mailto: "%env(json:SELFSIGNME_SURVEY_MAILTO)%"
#      local: []
#      remote: "%env(SELFSIGNME_SURVEY_REMOTE)%"
##    csr:
##                    countryName: "FR"
##                    stateOrProvinceName: "ILEDEFRANCE"
##                    localityName: "PARIS"
##                    organizationName: "GENDARMERIE NATIONALE"
##                    organizationalUnitName: "SDML"
##                    commonName: null
##                    emailAddress: "samir.keriou@gendarmerie.interieur.gouv.fr"
